/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeracionComunidadRouteImport } from './routes/moderacion.comunidad'

const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeracionComunidadRoute = ModeracionComunidadRouteImport.update({
  id: '/moderacion/comunidad',
  path: '/moderacion/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/moderacion/comunidad': typeof ModeracionComunidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/moderacion/comunidad': typeof ModeracionComunidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/moderacion/comunidad': typeof ModeracionComunidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/restablecer-contrasena' | '/moderacion/comunidad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/restablecer-contrasena' | '/moderacion/comunidad'
  id: '__root__' | '/' | '/restablecer-contrasena' | '/moderacion/comunidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  ModeracionComunidadRoute: typeof ModeracionComunidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderacion/comunidad': {
      id: '/moderacion/comunidad'
      path: '/moderacion/comunidad'
      fullPath: '/moderacion/comunidad'
      preLoaderRoute: typeof ModeracionComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  ModeracionComunidadRoute: ModeracionComunidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
