/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeracionComunidadRouteImport } from './routes/moderacion.comunidad'
import { Route as ApiPublicHooksNotificationsSchedulerRouteImport } from './routes/api/public/hooks/notifications-scheduler'
import { Route as ApiPublicHooksInstallCronRouteImport } from './routes/api/public/hooks/_install-cron'

const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeracionComunidadRoute = ModeracionComunidadRouteImport.update({
  id: '/moderacion/comunidad',
  path: '/moderacion/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotificationsSchedulerRoute =
  ApiPublicHooksNotificationsSchedulerRouteImport.update({
    id: '/api/public/hooks/notifications-scheduler',
    path: '/api/public/hooks/notifications-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInstallCronRoute =
  ApiPublicHooksInstallCronRouteImport.update({
    id: '/api/public/hooks/_install-cron',
    path: '/api/public/hooks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/moderacion/comunidad': typeof ModeracionComunidadRoute
  '/api/public/hooks': typeof ApiPublicHooksInstallCronRoute
  '/api/public/hooks/notifications-scheduler': typeof ApiPublicHooksNotificationsSchedulerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/moderacion/comunidad': typeof ModeracionComunidadRoute
  '/api/public/hooks': typeof ApiPublicHooksInstallCronRoute
  '/api/public/hooks/notifications-scheduler': typeof ApiPublicHooksNotificationsSchedulerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/moderacion/comunidad': typeof ModeracionComunidadRoute
  '/api/public/hooks/_install-cron': typeof ApiPublicHooksInstallCronRoute
  '/api/public/hooks/notifications-scheduler': typeof ApiPublicHooksNotificationsSchedulerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/restablecer-contrasena'
    | '/moderacion/comunidad'
    | '/api/public/hooks'
    | '/api/public/hooks/notifications-scheduler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/restablecer-contrasena'
    | '/moderacion/comunidad'
    | '/api/public/hooks'
    | '/api/public/hooks/notifications-scheduler'
  id:
    | '__root__'
    | '/'
    | '/restablecer-contrasena'
    | '/moderacion/comunidad'
    | '/api/public/hooks/_install-cron'
    | '/api/public/hooks/notifications-scheduler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  ModeracionComunidadRoute: typeof ModeracionComunidadRoute
  ApiPublicHooksInstallCronRoute: typeof ApiPublicHooksInstallCronRoute
  ApiPublicHooksNotificationsSchedulerRoute: typeof ApiPublicHooksNotificationsSchedulerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderacion/comunidad': {
      id: '/moderacion/comunidad'
      path: '/moderacion/comunidad'
      fullPath: '/moderacion/comunidad'
      preLoaderRoute: typeof ModeracionComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notifications-scheduler': {
      id: '/api/public/hooks/notifications-scheduler'
      path: '/api/public/hooks/notifications-scheduler'
      fullPath: '/api/public/hooks/notifications-scheduler'
      preLoaderRoute: typeof ApiPublicHooksNotificationsSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/_install-cron': {
      id: '/api/public/hooks/_install-cron'
      path: '/api/public/hooks'
      fullPath: '/api/public/hooks'
      preLoaderRoute: typeof ApiPublicHooksInstallCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  ModeracionComunidadRoute: ModeracionComunidadRoute,
  ApiPublicHooksInstallCronRoute: ApiPublicHooksInstallCronRoute,
  ApiPublicHooksNotificationsSchedulerRoute:
    ApiPublicHooksNotificationsSchedulerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
